- name: Create tmp jenkins directory
  file: path=/tmp/jenkins state=directory mode=0777

- name: check if jenkins home volume exists
  command: docker volume inspect jenkins_home
  register: jenkins_home_exists
  failed_when: false

- name: create jenkins_home
  command: docker volume create --name jenkins_home
  when: jenkins_home_exists|failed

- name: Copy jenkins dockerfile
  template: src=Dockerfile dest=/tmp/jenkins/Dockerfile force=yes

- name: Create the jenkins container image
  docker_image:
    path: /tmp/jenkins
    name: biblicando/jenkins
    state: present
    tag: latest
    push: no

- name: Create a Jenkins container
  docker_container:
    name: jenkins
    image: biblicando/jenkins
    state: started
    restart: no
    ports:
      - "8080:{{ jenkins_http_port }}"
      - "50000:50000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jenkins_home:/var/jenkins_home"

- name: Get name to unblock jenkins
  command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: initial_jenkins_admin_pass

- name: Print initial admin password
  debug: msg="Jenkins is installed. Give this password when it asks for {{ initial_jenkins_admin_pass }}"